# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagec', '0002_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='my loaction default', max_length=120),
        ),
    ]
