# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagec', '0004_profile_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='my loaction default', max_length=120, null=True),
        ),
    ]
