# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagec', '0009_auto_20170401_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='AboutMe',
            field=models.CharField(max_length=200),
        ),
    ]
